export const editorTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'editor-placeholder',
  paragraph: 'mb-4 leading-relaxed font-sans text-stone-300 text-[15px]',
  quote: 'border-l-2 border-accent bg-zinc-900/40 p-4 my-4 font-sans italic text-stone-400 rounded-r-lg',
  heading: {
    h1: 'text-2xl md:text-3xl font-sans font-bold tracking-tight text-white mt-6 mb-3',
    h2: 'text-xl md:text-2xl font-sans font-bold tracking-tight text-white mt-5 mb-3',
    h3: 'text-lg md:text-xl font-sans font-semibold tracking-tight text-white mt-4 mb-2',
    h4: 'text-base font-sans font-semibold tracking-tight text-white mt-4 mb-2',
    h5: 'text-sm font-sans font-semibold tracking-tight text-white mt-4 mb-2',
  },
  list: {
    nested: {
      listitem: 'list-none pl-4',
    },
    ol: 'list-decimal pl-6 my-4 space-y-1 font-sans text-stone-300 text-[15px]',
    ul: 'list-disc pl-6 my-4 space-y-1 font-sans text-stone-300 text-[15px]',
    listitem: 'pl-1 leading-relaxed',
  },
  image: 'lexical-image-element select-none',
  link: 'text-accent hover:text-accent-light underline underline-offset-4 cursor-pointer font-sans transition duration-150',
  text: {
    bold: 'font-bold text-white',
    italic: 'italic',
    overflowed: 'editor-text-overflowed',
    hashtag: 'editor-text-hashtag',
    underline: 'underline underline-offset-4',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'font-mono text-xs bg-zinc-900 border border-zinc-800 px-1.5 py-0.5 rounded text-accent-light mx-0.5',
  },
  code: 'font-mono text-xs block overflow-x-auto bg-zinc-950/80 border border-zinc-900/60 p-4 rounded-xl text-zinc-300 my-6 leading-relaxed selection:bg-indigo-500/20 whitespace-pre editor-code-block',
  codeHighlight: {
    atrule: 'text-[#f4f4f5]',
    attr: 'text-[#a1a1aa]',
    boolean: 'text-[#ef4444]',
    builtin: 'text-[#f59e0b]',
    cdata: 'text-[#a1a1aa]',
    char: 'text-[#10b981]',
    class: 'text-[#6366f1]',
    'class-name': 'text-[#6366f1]',
    comment: 'text-zinc-600 italic',
    constant: 'text-[#f59e0b]',
    deleted: 'text-[#ef4444]',
    doctype: 'text-[#f4f4f5]',
    entity: 'text-[#f4f4f5]',
    function: 'text-[#6366f1]',
    important: 'text-[#f59e0b]',
    inserted: 'text-[#10b981]',
    keyword: 'text-accent-light font-semibold',
    namespace: 'text-[#f4f4f5]',
    number: 'text-[#10b981]',
    operator: 'text-zinc-400',
    prolog: 'text-[#a1a1aa]',
    property: 'text-[#a1a1aa]',
    punctuation: 'text-zinc-500',
    regex: 'text-[#ef4444]',
    selector: 'text-[#10b981]',
    string: 'text-[#10b981]',
    symbol: 'text-[#f59e0b]',
    tag: 'text-[#ef4444]',
    url: 'text-[#10b981]',
    variable: 'text-[#a1a1aa]',
  },
};
